/* The following code was generated by JFlex 1.6.1 */

package Lexer;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import Utilities.Token;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Lexer/Lexer.flex</tt>
 */
public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\4\1\5\2\0\1\2\22\0\1\4\1\0\1\3\1\1"+
    "\1\7\1\11\1\7\1\47\1\16\1\16\1\11\1\11\1\16\1\11"+
    "\1\16\1\11\1\44\11\43\1\12\1\16\1\14\1\13\1\15\1\0"+
    "\1\7\4\46\1\33\1\42\10\6\1\41\10\6\1\45\2\6\1\16"+
    "\1\7\1\16\1\0\1\10\1\0\1\25\1\27\1\17\1\34\1\30"+
    "\1\35\1\31\1\36\1\32\2\6\1\37\1\6\1\21\1\20\2\6"+
    "\1\26\1\22\1\23\1\6\1\24\1\40\1\45\2\6\104\0\1\7"+
    "\1\0\1\7\7\0\1\7\3\0\1\7\3\0\1\7\1\0\1\7"+
    "\6\0\1\7\5\0\1\7\1\7\2\0\1\7\3\0\1\7\1\7"+
    "\1\0\1\7\1\7\1\7\1\0\1\7\1\0\1\7\1\7\1\7"+
    "\2\0\1\7\2\0\1\7\1\7\1\0\1\7\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff13\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\2\1\3\1\4\1\5"+
    "\1\1\2\5\1\6\16\3\2\7\1\1\1\0\1\10"+
    "\1\4\1\3\1\11\1\3\1\12\6\3\1\13\2\3"+
    "\1\14\3\3\2\15\1\0\1\10\1\0\1\15\1\3"+
    "\1\16\1\3\1\17\1\20\3\3\1\21\1\22\1\23"+
    "\2\3\2\15\3\7\1\10\2\15\2\0\1\15\1\3"+
    "\1\24\1\25\1\3\1\26\2\3\2\15\1\0\1\15"+
    "\1\27\1\3\1\30\1\31\1\32\2\15\1\0\1\2"+
    "\2\3\1\15\2\3\1\33\1\3\1\34";

  private static int [] zzUnpackAction() {
    int [] result = new int[108];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\240\0\50\0\310\0\360"+
    "\0\50\0\u0118\0\u0140\0\u0118\0\50\0\u0168\0\u0190\0\u01b8"+
    "\0\u01e0\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8"+
    "\0\u0320\0\u0348\0\u0370\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438"+
    "\0\u0460\0\u0488\0\310\0\u04b0\0\310\0\u04d8\0\u0500\0\u0528"+
    "\0\u0550\0\u0578\0\u05a0\0\310\0\u05c8\0\u05f0\0\310\0\u0618"+
    "\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730\0\u0758"+
    "\0\u0780\0\310\0\u07a8\0\310\0\310\0\u07d0\0\u07f8\0\u0820"+
    "\0\310\0\310\0\310\0\u0848\0\u0870\0\u0898\0\u08c0\0\u06b8"+
    "\0\u08e8\0\u0910\0\50\0\u0708\0\50\0\u0938\0\u0960\0\u0988"+
    "\0\u09b0\0\310\0\u09d8\0\u0a00\0\310\0\u0a28\0\u0a50\0\u0a78"+
    "\0\u0aa0\0\u0aa0\0\u0ac8\0\310\0\u0af0\0\310\0\u0b18\0\310"+
    "\0\u0b40\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08\0\u0bb8\0\u0c30"+
    "\0\u0c58\0\310\0\u0c80\0\310";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[108];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\6\1\7\1\2\1\10"+
    "\1\11\1\12\1\11\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\7\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\7\1\27\1\30\1\31\1\32\2\7\1\33\2\7"+
    "\1\34\1\35\2\7\1\36\50\0\2\3\1\0\2\3"+
    "\1\0\42\3\5\0\1\6\42\0\2\37\1\0\1\40"+
    "\1\37\1\0\42\37\6\0\1\7\1\0\1\7\6\0"+
    "\30\7\7\0\1\41\1\10\7\0\24\41\2\0\2\41"+
    "\14\0\1\11\47\0\1\11\1\0\1\11\40\0\1\7"+
    "\1\0\1\7\6\0\1\7\1\42\26\7\7\0\1\7"+
    "\1\0\1\7\6\0\7\7\1\43\20\7\7\0\1\7"+
    "\1\0\1\7\6\0\1\7\1\44\26\7\7\0\1\7"+
    "\1\0\1\7\6\0\1\7\1\45\15\7\1\46\10\7"+
    "\7\0\1\7\1\0\1\7\6\0\6\7\1\47\21\7"+
    "\7\0\1\7\1\0\1\7\6\0\2\7\1\50\25\7"+
    "\7\0\1\7\1\0\1\7\6\0\11\7\1\51\16\7"+
    "\7\0\1\7\1\0\1\7\6\0\11\7\1\52\16\7"+
    "\7\0\1\7\1\0\1\7\6\0\20\7\1\53\7\7"+
    "\7\0\1\7\1\0\1\7\6\0\16\7\1\54\11\7"+
    "\7\0\1\7\1\0\1\7\6\0\2\7\1\55\17\7"+
    "\1\56\5\7\7\0\1\7\1\0\1\7\6\0\1\7"+
    "\1\57\26\7\7\0\1\7\1\0\1\7\6\0\1\7"+
    "\1\60\26\7\7\0\1\7\1\0\1\7\6\0\7\7"+
    "\1\61\7\7\1\62\10\7\7\0\3\63\6\0\24\63"+
    "\2\34\2\63\7\0\3\63\6\0\24\63\2\0\1\64"+
    "\1\63\1\0\47\65\1\0\2\37\1\0\1\66\1\37"+
    "\1\0\42\37\2\67\1\0\1\70\1\67\1\0\42\67"+
    "\6\0\1\41\1\10\1\41\6\0\30\41\7\0\1\7"+
    "\1\0\1\7\6\0\2\7\1\71\25\7\7\0\1\7"+
    "\1\0\1\7\6\0\4\7\1\72\23\7\7\0\1\7"+
    "\1\0\1\7\6\0\11\7\1\73\16\7\7\0\1\7"+
    "\1\0\1\7\6\0\7\7\1\74\20\7\7\0\1\7"+
    "\1\0\1\7\6\0\15\7\1\75\12\7\7\0\1\7"+
    "\1\0\1\7\6\0\6\7\1\76\21\7\7\0\1\7"+
    "\1\0\1\7\6\0\12\7\1\77\15\7\7\0\1\7"+
    "\1\0\1\7\6\0\3\7\1\100\24\7\7\0\1\7"+
    "\1\0\1\7\6\0\15\7\1\101\12\7\7\0\1\7"+
    "\1\0\1\7\6\0\23\7\1\102\4\7\7\0\1\7"+
    "\1\0\1\7\6\0\7\7\1\103\20\7\7\0\1\7"+
    "\1\0\1\7\6\0\13\7\1\104\14\7\7\0\1\7"+
    "\1\0\1\7\6\0\13\7\1\105\14\7\7\0\3\63"+
    "\6\0\24\63\1\106\1\107\2\63\7\0\3\63\6\0"+
    "\1\110\5\63\1\110\1\63\2\110\2\63\3\110\4\63"+
    "\1\110\1\111\1\112\1\63\1\110\50\0\1\113\3\0"+
    "\1\114\44\0\2\67\1\0\1\115\1\67\1\0\42\67"+
    "\2\116\1\117\1\120\1\116\1\117\42\116\6\0\1\7"+
    "\1\0\1\7\6\0\3\7\1\121\24\7\7\0\1\7"+
    "\1\0\1\7\6\0\2\7\1\122\25\7\7\0\1\7"+
    "\1\0\1\7\6\0\15\7\1\123\12\7\7\0\1\7"+
    "\1\0\1\7\6\0\13\7\1\124\14\7\7\0\1\7"+
    "\1\0\1\7\6\0\11\7\1\125\16\7\7\0\1\7"+
    "\1\0\1\7\6\0\4\7\1\126\23\7\7\0\1\7"+
    "\1\0\1\7\6\0\20\7\1\127\7\7\7\0\3\63"+
    "\6\0\24\63\2\106\2\63\7\0\3\63\6\0\24\63"+
    "\2\0\1\130\1\63\7\0\3\63\6\0\1\110\5\63"+
    "\1\110\1\63\2\110\2\63\3\110\4\63\1\110\2\111"+
    "\1\63\1\110\7\0\3\63\6\0\1\110\5\63\1\110"+
    "\1\63\2\110\2\63\3\110\4\63\1\110\2\111\1\130"+
    "\1\110\1\0\2\116\1\117\1\131\1\116\1\117\42\116"+
    "\3\117\1\132\44\117\2\67\1\0\1\133\1\67\1\0"+
    "\42\67\6\0\1\7\1\0\1\7\6\0\4\7\1\134"+
    "\23\7\7\0\1\7\1\0\1\7\6\0\1\135\27\7"+
    "\7\0\1\7\1\0\1\7\6\0\2\7\1\136\25\7"+
    "\7\0\1\7\1\0\1\7\6\0\11\7\1\137\16\7"+
    "\7\0\1\7\1\0\1\7\6\0\11\7\1\140\16\7"+
    "\7\0\3\63\6\0\1\130\5\63\1\130\1\63\2\130"+
    "\2\63\3\130\4\63\1\130\1\141\1\142\1\63\1\130"+
    "\4\0\1\143\44\0\2\67\1\0\1\144\1\67\1\0"+
    "\42\67\6\0\1\7\1\0\1\7\6\0\17\7\1\145"+
    "\10\7\7\0\1\7\1\0\1\7\6\0\1\146\27\7"+
    "\7\0\3\63\6\0\1\130\5\63\1\130\1\63\2\130"+
    "\2\63\3\130\4\63\1\130\2\141\1\63\1\130\7\0"+
    "\3\63\6\0\1\130\5\63\1\130\1\63\2\130\2\63"+
    "\3\130\4\63\1\130\2\141\2\130\4\0\1\6\44\0"+
    "\2\67\1\0\1\147\1\67\1\0\42\67\6\0\1\7"+
    "\1\0\1\7\6\0\6\7\1\150\21\7\7\0\1\7"+
    "\1\0\1\7\6\0\17\7\1\151\10\7\7\0\1\7"+
    "\1\0\1\7\6\0\7\7\1\152\20\7\7\0\1\7"+
    "\1\0\1\7\6\0\6\7\1\153\21\7\7\0\1\7"+
    "\1\0\1\7\6\0\7\7\1\154\20\7\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3240];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\1\11\3\1\1\11"+
    "\21\1\1\0\25\1\1\0\1\1\1\0\23\1\1\11"+
    "\1\1\1\11\2\0\12\1\1\0\10\1\1\0\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[108];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private ArrayList<Token> tokens;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
      tokens = new ArrayList<Token>();
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 248) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { Token t = new Token(yytext(),"ERROR, unrecognized token",yyline,yycolumn);tokens.add(t);return t;
            }
          case 29: break;
          case 2: 
            { /*Ignore*/
            }
          case 30: break;
          case 3: 
            { Token t = new Token(yytext(),"Identifier",yyline,yycolumn);tokens.add(t);return t;
            }
          case 31: break;
          case 4: 
            { Token t = new Token(yytext(),"ERROR, invalid identifier",yyline,yycolumn);tokens.add(t);return t;
            }
          case 32: break;
          case 5: 
            { Token t = new Token(yytext(),"Operator",yyline,yycolumn);tokens.add(t);return t;
            }
          case 33: break;
          case 6: 
            { Token t = new Token(yytext(),"Separator",yyline,yycolumn);tokens.add(t);return t;
            }
          case 34: break;
          case 7: 
            { Token t = new Token(yytext(),"Number",yyline,yycolumn);tokens.add(t);return t;
            }
          case 35: break;
          case 8: 
            { Token t = new Token(yytext(),"String",yyline,yycolumn);tokens.add(t);return t;
            }
          case 36: break;
          case 9: 
            { Token t = new Token(yytext(),"Or: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 37: break;
          case 10: 
            { Token t = new Token(yytext(),"To: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 38: break;
          case 11: 
            { Token t = new Token(yytext(),"If: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 39: break;
          case 12: 
            { Token t = new Token(yytext(),"Do: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 40: break;
          case 13: 
            { Token t = new Token(yytext(),"ERROR, invalid literal",yyline,yycolumn);tokens.add(t);return t;
            }
          case 41: break;
          case 14: 
            { Token t = new Token(yytext(),"Not: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 42: break;
          case 15: 
            { Token t = new Token(yytext(),"Var: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 43: break;
          case 16: 
            { Token t = new Token(yytext(),"And: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 44: break;
          case 17: 
            { Token t = new Token(yytext(),"End: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 45: break;
          case 18: 
            { Token t = new Token(yytext(),"EOF",yyline,yycolumn);tokens.add(t);return t;
            }
          case 46: break;
          case 19: 
            { Token t = new Token(yytext(),"For: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 47: break;
          case 20: 
            { Token t = new Token(yytext(),"Then: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 48: break;
          case 21: 
            { Token t = new Token(yytext(),"Read: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 49: break;
          case 22: 
            { Token t = new Token(yytext(),"Else: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 50: break;
          case 23: 
            { Token t = new Token(yytext(),"Const: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 51: break;
          case 24: 
            { Token t = new Token(yytext(),"Begin: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 52: break;
          case 25: 
            { Token t = new Token(yytext(),"Write: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 53: break;
          case 26: 
            { Token t = new Token(yytext(),"While: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 54: break;
          case 27: 
            { Token t = new Token(yytext(),"Readchar: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 55: break;
          case 28: 
            { Token t = new Token(yytext(),"Writechar: Reserved word",yyline,yycolumn);tokens.add(t);return t;
            }
          case 56: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
