/* The following code was generated by JFlex 1.6.1 */

package Lexer;

import Utilities.Token;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/lexer/Lexer.flex</tt>
 */
public class Lexer {

    /** This character denotes the end of file */
    public static final int YYEOF = -1;

    /** initial size of the lookahead buffer */
    private static final int ZZ_BUFFERSIZE = 16384;

    /** lexical states */
    public static final int YYINITIAL = 0;

    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
     *                  at the beginning of a line
     * l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = {
            0, 0
    };

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED =
            "\11\0\1\4\1\5\2\0\1\2\22\0\1\4\1\15\1\3\1\1"+
                    "\1\10\1\7\1\10\1\62\1\21\1\21\1\12\1\11\1\21\1\11"+
                    "\1\60\1\13\1\51\1\57\6\53\2\50\1\21\1\0\1\16\1\14"+
                    "\1\17\1\0\1\10\1\55\1\56\2\55\1\61\1\65\7\6\1\63"+
                    "\1\52\4\6\1\64\3\6\1\54\2\6\1\21\1\10\1\21\1\20"+
                    "\1\6\1\0\1\22\1\41\1\46\1\24\1\25\1\27\1\40\1\35"+
                    "\1\36\1\6\1\44\1\26\1\32\1\23\1\31\1\42\1\6\1\30"+
                    "\1\37\1\33\1\47\1\6\1\34\1\45\1\43\1\6\1\0\1\20"+
                    "\1\0\1\20\100\0\1\10\1\0\1\10\7\0\1\10\3\0\1\10"+
                    "\3\0\1\10\1\0\1\10\6\0\1\10\5\0\1\10\1\10\2\0"+
                    "\1\10\3\0\1\10\1\10\1\0\1\10\1\10\1\10\1\0\1\10"+
                    "\1\0\1\10\1\10\1\10\2\0\1\10\2\0\1\10\1\10\1\0"+
                    "\1\10\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff13\0";

    /**
     * Translates characters to character classes
     */
    private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

    /**
     * Translates DFA states to action switch labels.
     */
    private static final int [] ZZ_ACTION = zzUnpackAction();

    private static final String ZZ_ACTION_PACKED_0 =
            "\1\0\1\1\2\2\1\1\1\2\1\3\1\4\1\5"+
                    "\6\4\1\6\21\3\2\7\2\1\3\3\1\0\1\10"+
                    "\1\5\1\3\1\11\12\3\1\11\3\3\1\11\11\3"+
                    "\2\12\1\7\3\12\3\0\3\3\1\10\1\0\1\12"+
                    "\15\3\1\13\7\3\2\12\2\0\7\7\1\0\1\10"+
                    "\1\0\3\3\2\12\2\0\1\12\11\3\3\12\3\7"+
                    "\1\12\1\14\1\15\1\12\1\0\1\12\5\3\4\12"+
                    "\1\0\1\2\1\3\3\12";

    private static int [] zzUnpackAction() {
        int [] result = new int[163];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int [] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /**
     * Translates a state to a row index in the transition table
     */
    private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\66\0\154\0\242\0\330\0\66\0\u010e\0\u0144"+
                    "\0\u0144\0\u017a\0\u01b0\0\u01e6\0\u021c\0\u0252\0\66\0\66"+
                    "\0\u0288\0\u02be\0\u02f4\0\u032a\0\u0360\0\u0396\0\u03cc\0\u0402"+
                    "\0\u0438\0\u046e\0\u04a4\0\u04da\0\u0510\0\u0546\0\u057c\0\u05b2"+
                    "\0\u05e8\0\u061e\0\u0654\0\u068a\0\u06c0\0\u06f6\0\u072c\0\u0762"+
                    "\0\u0798\0\u07ce\0\u0804\0\u083a\0\u0870\0\u08a6\0\u08dc\0\u0912"+
                    "\0\u0948\0\u097e\0\u09b4\0\u09ea\0\u0a20\0\u0a56\0\u0a8c\0\u010e"+
                    "\0\u0ac2\0\u0af8\0\u0b2e\0\u0b64\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c"+
                    "\0\u0c72\0\u0ca8\0\u0cde\0\u0d14\0\u0d4a\0\u0d80\0\u0db6\0\u0dec"+
                    "\0\u0e22\0\u0e58\0\u0e8e\0\u0ec4\0\u0efa\0\u0f30\0\u0f66\0\u0f9c"+
                    "\0\u0fd2\0\u1008\0\u103e\0\u1074\0\u10aa\0\u10e0\0\u1116\0\u114c"+
                    "\0\u1182\0\u11b8\0\u11ee\0\u1224\0\u125a\0\u1290\0\u12c6\0\u12fc"+
                    "\0\u1332\0\u010e\0\u1368\0\u139e\0\u13d4\0\u140a\0\u1440\0\u1476"+
                    "\0\u14ac\0\u14e2\0\u1518\0\u154e\0\u1584\0\u15ba\0\u15f0\0\u1626"+
                    "\0\u165c\0\u0e8e\0\u1692\0\u16c8\0\u16fe\0\u1734\0\u176a\0\u17a0"+
                    "\0\u17d6\0\u180c\0\u1008\0\66\0\u1842\0\u1878\0\u18ae\0\u18e4"+
                    "\0\u191a\0\u1950\0\u0b64\0\u1986\0\u19bc\0\u19f2\0\u1a28\0\u1a5e"+
                    "\0\u1a94\0\u1aca\0\u1b00\0\u154e\0\u1b36\0\u1b6c\0\u1734\0\u010e"+
                    "\0\u010e\0\u1ba2\0\u1ba2\0\u1bd8\0\u1c0e\0\u1c44\0\u1c7a\0\u1cb0"+
                    "\0\u1ce6\0\u1d1c\0\u1d52\0\u1d88\0\u1dbe\0\u1df4\0\u1e2a\0\u1e60"+
                    "\0\u1e96\0\u1ecc\0\u1e2a";

    private static int [] zzUnpackRowMap() {
        int [] result = new int[163];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int [] result) {
        int i = 0;  /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    /**
     * The transition table of the DFA
     */
    private static final int [] ZZ_TRANS = zzUnpackTrans();

    private static final String ZZ_TRANS_PACKED_0 =
            "\1\2\1\3\1\4\1\5\2\6\1\7\1\10\1\11"+
                    "\1\12\1\13\1\14\2\12\1\15\1\16\1\17\1\20"+
                    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
                    "\1\7\1\31\1\32\1\7\1\33\1\34\1\35\1\36"+
                    "\1\37\1\40\2\7\1\41\1\7\1\42\1\43\1\7"+
                    "\1\42\3\7\1\42\1\44\1\7\1\45\1\46\1\47"+
                    "\1\50\66\0\2\3\1\0\2\3\1\0\60\3\5\0"+
                    "\1\6\60\0\2\51\1\0\1\52\1\51\1\0\60\51"+
                    "\6\0\1\7\2\11\11\0\36\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\53\2\11\11\0\26\53\2\0\1\53"+
                    "\1\0\3\53\2\0\1\53\1\0\3\53\14\0\1\17"+
                    "\63\0\1\12\1\0\1\17\64\0\1\12\1\17\65\0"+
                    "\1\17\1\0\2\17\62\0\1\17\2\0\1\17\54\0"+
                    "\1\7\2\11\11\0\1\7\1\54\13\7\1\55\20\7"+
                    "\1\0\1\7\1\0\3\7\6\0\1\7\2\11\11\0"+
                    "\7\7\1\56\26\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\3\7\1\57\32\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\4\7\1\60"+
                    "\16\7\1\61\12\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\1\62\35\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\4\7\1\63\1\7"+
                    "\1\64\1\30\4\7\1\65\21\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\1\66\2\7\1\67"+
                    "\32\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\6\7\1\70\27\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\6\7\1\71\27\7\1\0"+
                    "\1\7\1\0\3\7\6\0\1\7\2\11\11\0\13\7"+
                    "\1\72\1\73\21\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\1\7\1\74\3\7\1\70\2\7"+
                    "\1\75\4\7\1\70\20\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\11\7\1\76\24\7\1\0"+
                    "\1\7\1\0\3\7\6\0\1\7\2\11\11\0\4\7"+
                    "\1\77\31\7\1\0\1\7\1\0\3\7\6\0\1\7"+
                    "\2\11\11\0\6\7\1\100\27\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\1\101\5\7\1\102"+
                    "\27\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\14\7\1\103\21\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\4\7\1\104\2\7\1\105"+
                    "\3\7\1\76\22\7\1\0\1\7\1\0\3\7\6\0"+
                    "\3\106\11\0\3\106\1\107\22\106\2\42\1\106\1\42"+
                    "\3\106\1\42\1\110\1\107\1\0\3\106\6\0\3\106"+
                    "\11\0\3\106\1\107\3\106\1\111\7\106\1\112\3\106"+
                    "\1\113\2\106\2\114\1\111\1\114\1\113\1\106\1\112"+
                    "\1\114\1\110\1\107\1\0\3\106\50\0\2\110\1\0"+
                    "\1\110\3\0\1\110\6\0\62\115\1\116\3\115\6\0"+
                    "\1\7\2\11\11\0\7\7\1\117\26\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\6\7\1\120"+
                    "\27\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\1\121\35\7\1\0\1\7\1\0\3\7\2\51"+
                    "\1\0\1\122\1\51\1\0\60\51\2\123\1\0\1\124"+
                    "\1\123\1\0\60\123\6\0\1\53\2\11\11\0\36\53"+
                    "\1\0\1\53\1\0\3\53\6\0\1\7\2\11\11\0"+
                    "\2\7\1\70\33\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\15\7\1\125\20\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\11\7\1\70"+
                    "\24\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\4\7\2\70\30\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\14\7\1\126\1\127\20\7"+
                    "\1\0\1\7\1\0\3\7\6\0\1\7\2\11\11\0"+
                    "\3\7\1\130\20\7\1\131\11\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\10\7\1\132\25\7"+
                    "\1\0\1\7\1\0\3\7\6\0\1\7\2\11\11\0"+
                    "\7\7\1\133\26\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\7\7\1\134\26\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\1\7\1\135"+
                    "\34\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\14\7\1\136\21\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\11\7\1\137\24\7\1\0"+
                    "\1\7\1\0\3\7\6\0\1\7\2\11\11\0\21\7"+
                    "\1\70\14\7\1\0\1\7\1\0\3\7\6\0\1\7"+
                    "\2\11\11\0\14\7\1\140\21\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\11\7\1\141\24\7"+
                    "\1\0\1\7\1\0\3\7\6\0\1\7\2\11\11\0"+
                    "\11\7\1\142\24\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\20\7\1\143\15\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\6\7\1\142"+
                    "\27\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\7\7\1\144\26\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\3\7\1\145\32\7\1\0"+
                    "\1\7\1\0\3\7\6\0\1\7\2\11\11\0\15\7"+
                    "\1\146\20\7\1\0\1\7\1\0\3\7\6\0\1\7"+
                    "\2\11\11\0\14\7\1\147\21\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\3\7\1\150\32\7"+
                    "\1\0\1\7\1\0\3\7\6\0\1\7\2\11\11\0"+
                    "\1\101\35\7\1\0\1\7\1\0\3\7\6\0\1\7"+
                    "\2\11\11\0\1\7\1\151\34\7\1\0\1\7\1\0"+
                    "\3\7\6\0\3\106\11\0\26\106\1\152\1\153\1\106"+
                    "\1\152\3\106\1\152\1\0\1\106\1\0\3\106\6\0"+
                    "\3\106\1\154\10\0\26\106\1\152\1\153\1\106\1\152"+
                    "\3\106\1\152\1\0\1\106\1\0\3\106\25\0\1\155"+
                    "\22\0\2\110\1\0\1\110\3\0\1\110\1\0\1\155"+
                    "\12\0\3\106\11\0\26\106\1\152\1\156\1\106\1\157"+
                    "\3\106\1\157\1\0\1\106\1\0\3\106\6\0\3\106"+
                    "\11\0\26\106\1\152\1\160\1\106\1\152\3\106\1\161"+
                    "\1\0\1\106\1\0\3\106\6\0\3\106\11\0\1\162"+
                    "\1\106\2\162\1\106\1\162\11\106\1\162\4\106\1\162"+
                    "\1\106\1\163\1\164\1\106\1\163\1\106\2\162\1\163"+
                    "\1\0\1\162\1\0\2\106\1\162\25\0\1\155\22\0"+
                    "\2\114\1\0\1\114\3\0\1\114\1\110\1\155\4\0"+
                    "\62\165\1\166\3\165\62\167\1\116\3\167\6\0\1\7"+
                    "\2\11\11\0\1\7\1\170\34\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\25\7\1\171\10\7"+
                    "\1\0\1\7\1\0\3\7\6\0\1\7\2\11\11\0"+
                    "\4\7\1\172\31\7\1\0\1\7\1\0\3\7\3\0"+
                    "\1\173\62\0\2\123\1\0\1\174\1\123\1\0\60\123"+
                    "\2\175\1\176\1\177\1\175\1\176\60\175\6\0\1\7"+
                    "\2\11\11\0\3\7\1\200\32\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\5\7\1\70\30\7"+
                    "\1\0\1\7\1\0\3\7\6\0\1\7\2\11\11\0"+
                    "\3\7\1\70\32\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\24\7\1\70\11\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\3\7\1\201"+
                    "\32\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\17\7\1\202\16\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\1\203\35\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\10\7\1\70"+
                    "\25\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\1\204\35\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\15\7\1\127\20\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\25\7\1\205"+
                    "\10\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\4\7\1\127\31\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\13\7\1\70\22\7\1\0"+
                    "\1\7\1\0\3\7\6\0\1\7\2\11\11\0\7\7"+
                    "\1\200\26\7\1\0\1\7\1\0\3\7\6\0\1\7"+
                    "\2\11\11\0\17\7\1\206\16\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\1\207\35\7\1\0"+
                    "\1\7\1\0\3\7\6\0\1\7\2\11\11\0\15\7"+
                    "\1\70\20\7\1\0\1\7\1\0\3\7\6\0\1\7"+
                    "\2\11\11\0\1\7\1\56\34\7\1\0\1\7\1\0"+
                    "\3\7\6\0\1\7\2\11\11\0\4\7\1\54\31\7"+
                    "\1\0\1\7\1\0\3\7\6\0\1\7\2\11\11\0"+
                    "\11\7\1\210\24\7\1\0\1\7\1\0\3\7\6\0"+
                    "\3\106\11\0\26\106\2\152\1\106\1\152\3\106\1\152"+
                    "\1\0\1\106\1\0\3\106\6\0\3\106\11\0\7\106"+
                    "\1\211\7\106\1\212\3\106\1\213\2\106\2\0\1\211"+
                    "\1\0\1\213\1\106\1\212\2\0\1\106\1\0\3\106"+
                    "\50\0\2\214\1\0\1\214\3\0\1\214\17\0\1\154"+
                    "\62\0\3\106\11\0\7\106\1\211\7\106\1\212\3\106"+
                    "\1\213\2\106\1\0\1\215\1\211\1\215\1\213\1\106"+
                    "\1\212\1\215\1\0\1\106\1\0\3\106\6\0\3\106"+
                    "\11\0\26\106\1\152\1\157\1\106\1\157\3\106\1\157"+
                    "\1\0\1\106\1\0\3\106\6\0\3\106\11\0\7\106"+
                    "\1\211\7\106\1\212\3\106\1\213\2\106\1\0\1\216"+
                    "\1\211\1\0\1\213\1\106\1\212\1\216\1\0\1\106"+
                    "\1\0\3\106\6\0\3\106\11\0\26\106\1\152\1\161"+
                    "\1\106\1\152\3\106\1\161\1\0\1\106\1\0\3\106"+
                    "\6\0\3\106\11\0\1\162\1\106\2\162\1\106\1\162"+
                    "\11\106\1\162\4\106\1\162\1\106\2\163\1\106\1\163"+
                    "\1\106\2\162\1\163\1\0\1\162\1\0\2\106\1\162"+
                    "\6\0\3\106\11\0\1\162\1\106\2\162\1\106\1\162"+
                    "\1\106\1\211\7\106\1\162\3\106\1\213\1\162\1\106"+
                    "\2\163\1\211\1\163\1\213\2\162\1\163\1\0\1\162"+
                    "\1\0\2\106\1\162\62\165\1\217\3\165\62\0\1\217"+
                    "\3\0\62\167\1\174\3\167\6\0\1\7\2\11\11\0"+
                    "\3\7\1\220\32\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\3\7\1\221\32\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\15\7\1\171"+
                    "\20\7\1\0\1\7\1\0\3\7\2\175\1\176\1\222"+
                    "\1\175\1\176\60\175\3\176\1\223\62\176\2\123\1\0"+
                    "\1\224\1\123\1\0\60\123\6\0\1\7\2\11\11\0"+
                    "\6\7\1\56\27\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\20\7\1\56\15\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\2\7\1\225"+
                    "\33\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\4\7\1\226\31\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\6\7\1\227\27\7\1\0"+
                    "\1\7\1\0\3\7\6\0\1\7\2\11\11\0\1\230"+
                    "\35\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\22\7\1\70\13\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\14\7\1\231\21\7\1\0"+
                    "\1\7\1\0\3\7\6\0\3\106\11\0\26\106\1\152"+
                    "\1\232\1\106\1\152\3\106\1\152\1\0\1\106\1\0"+
                    "\3\106\6\0\3\106\11\0\26\106\1\152\1\233\1\106"+
                    "\1\152\3\106\1\152\1\0\1\106\1\0\3\106\6\0"+
                    "\3\106\11\0\1\213\1\106\2\213\1\106\1\213\11\106"+
                    "\1\213\4\106\1\213\1\106\1\234\1\235\1\106\1\234"+
                    "\1\106\2\213\1\234\1\0\1\213\1\0\2\106\1\213"+
                    "\6\0\3\106\11\0\26\106\1\0\1\215\1\106\1\215"+
                    "\3\106\1\215\1\0\1\106\1\0\3\106\6\0\3\106"+
                    "\11\0\26\106\1\0\1\216\1\106\1\0\3\106\1\216"+
                    "\1\0\1\106\1\0\3\106\3\0\1\236\62\0\2\123"+
                    "\1\0\1\237\1\123\1\0\60\123\6\0\1\7\2\11"+
                    "\11\0\1\70\35\7\1\0\1\7\1\0\3\7\6\0"+
                    "\1\7\2\11\11\0\4\7\1\71\31\7\1\0\1\7"+
                    "\1\0\3\7\6\0\1\7\2\11\11\0\1\7\1\70"+
                    "\34\7\1\0\1\7\1\0\3\7\6\0\1\7\2\11"+
                    "\11\0\4\7\1\70\31\7\1\0\1\7\1\0\3\7"+
                    "\6\0\1\7\2\11\11\0\1\7\1\240\34\7\1\0"+
                    "\1\7\1\0\3\7\6\0\3\106\11\0\7\106\1\211"+
                    "\7\106\1\212\3\106\1\213\2\106\1\0\1\241\1\211"+
                    "\1\241\1\213\1\106\1\212\1\241\1\0\1\106\1\0"+
                    "\3\106\6\0\3\106\11\0\7\106\1\211\7\106\1\212"+
                    "\3\106\1\213\2\106\1\0\1\242\1\211\1\0\1\213"+
                    "\1\106\1\212\1\242\1\0\1\106\1\0\3\106\6\0"+
                    "\3\106\11\0\1\213\1\106\2\213\1\106\1\213\11\106"+
                    "\1\213\4\106\1\213\1\106\2\234\1\106\1\234\1\106"+
                    "\2\213\1\234\1\0\1\213\1\0\2\106\1\213\6\0"+
                    "\3\106\11\0\1\213\1\106\2\213\1\106\1\213\1\106"+
                    "\1\211\7\106\1\213\3\106\2\213\1\106\2\234\1\211"+
                    "\1\234\3\213\1\234\1\0\1\213\1\0\2\106\1\213"+
                    "\3\0\1\6\62\0\2\123\1\0\1\243\1\123\1\0"+
                    "\60\123\6\0\1\7\2\11\11\0\25\7\1\127\10\7"+
                    "\1\0\1\7\1\0\3\7\6\0\3\106\11\0\26\106"+
                    "\1\0\1\241\1\106\1\241\3\106\1\241\1\0\1\106"+
                    "\1\0\3\106\6\0\3\106\11\0\26\106\1\0\1\242"+
                    "\1\106\1\0\3\106\1\242\1\0\1\106\1\0\3\106";

    private static int [] zzUnpackTrans() {
        int [] result = new int[7938];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int [] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }


    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;

    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = {
            "Unknown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
    };

    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

    private static final String ZZ_ATTRIBUTE_PACKED_0 =
            "\1\0\1\11\3\1\1\11\10\1\2\11\30\1\1\0"+
                    "\42\1\3\0\4\1\1\0\30\1\2\0\7\1\1\0"+
                    "\1\1\1\0\4\1\1\11\2\0\24\1\1\0\12\1"+
                    "\1\0\5\1";

    private static int [] zzUnpackAttribute() {
        int [] result = new int[163];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int [] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /** the input device */
    private java.io.Reader zzReader;

    /** the current state of the DFA */
    private int zzState;

    /** the current lexical state */
    private int zzLexicalState = YYINITIAL;

    /** this buffer contains the current text to be matched and is
     the source of the yytext() string */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

    /** the textposition at the last accepting state */
    private int zzMarkedPos;

    /** the current text position in the buffer */
    private int zzCurrentPos;

    /** startRead marks the beginning of the yytext() string in the buffer */
    private int zzStartRead;

    /** endRead marks the last character in the buffer, that has been read
     from input */
    private int zzEndRead;

    /** number of newlines encountered up to the start of the matched text */
    private int yyline;

    /** the number of characters up to the start of the matched text */
    private int yychar;

    /**
     * the number of characters from the last newline up to the start of the
     * matched text
     */
    private int yycolumn;

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;

    /** zzAtEOF == true <=> the scanner is at the EOF */
    private boolean zzAtEOF;

    /** denotes if the user-EOF-code has already been executed */
    private boolean zzEOFDone;

    /**
     * The number of occupied positions in zzBuffer beyond zzEndRead.
     * When a lead/high surrogate has been read from the input stream
     * into the final zzBuffer position, this will have a value of 1;
     * otherwise, it will have a value of 0.
     */
    private int zzFinalHighSurrogate = 0;

    /* user code: */
    private ArrayList<Token> tokens;


    /**
     * Creates a new scanner
     *
     * @param   in  the java.io.Reader to read input from.
     */
    public Lexer(java.io.Reader in) {
        tokens = new ArrayList<Token>();
        this.zzReader = in;
    }


    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed   the packed character translation table
     * @return         the unpacked character translation table
     */
    private static char [] zzUnpackCMap(String packed) {
        char [] map = new char[0x110000];
        int i = 0;  /* index in packed string  */
        int j = 0;  /* index in unpacked array */
        while (i < 276) {
            int  count = packed.charAt(i++);
            char value = packed.charAt(i++);
            do map[j++] = value; while (--count > 0);
        }
        return map;
    }


    /**
     * Refills the input buffer.
     *
     * @return      <code>false</code>, iff there was new input.
     *
     * @exception   java.io.IOException  if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {

        /* first: make room (if you can) */
        if (zzStartRead > 0) {
            zzEndRead += zzFinalHighSurrogate;
            zzFinalHighSurrogate = 0;
            System.arraycopy(zzBuffer, zzStartRead,
                    zzBuffer, 0,
                    zzEndRead-zzStartRead);

            /* translate stored positions */
            zzEndRead-= zzStartRead;
            zzCurrentPos-= zzStartRead;
            zzMarkedPos-= zzStartRead;
            zzStartRead = 0;
        }

        /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
            /* if not: blow it up */
            char newBuffer[] = new char[zzBuffer.length*2];
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
            zzBuffer = newBuffer;
            zzEndRead += zzFinalHighSurrogate;
            zzFinalHighSurrogate = 0;
        }

        /* fill the buffer with new input */
        int requested = zzBuffer.length - zzEndRead;
        int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

        /* not supposed to occur according to specification of java.io.Reader */
        if (numRead == 0) {
            throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
        }
        if (numRead > 0) {
            zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
            if (numRead == requested) {
                if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
                    --zzEndRead;
                    zzFinalHighSurrogate = 1;
                }
            }
            /* potentially more input available */
            return false;
        }

        /* numRead < 0 ==> end of stream */
        return true;
    }


    /**
     * Closes the input stream.
     */
    public final void yyclose() throws java.io.IOException {
        zzAtEOF = true;            /* indicate end of file */
        zzEndRead = zzStartRead;  /* invalidate buffer    */

        if (zzReader != null)
            zzReader.close();
    }


    /**
     * Resets the scanner to read from a new input stream.
     * Does not close the old reader.
     *
     * All internal variables are reset, the old input stream
     * <b>cannot</b> be reused (internal buffer is discarded and lost).
     * Lexical state is set to <tt>ZZ_INITIAL</tt>.
     *
     * Internal scan buffer is resized down to its initial length, if it has grown.
     *
     * @param reader   the new input stream
     */
    public final void yyreset(java.io.Reader reader) {
        zzReader = reader;
        zzAtBOL  = true;
        zzAtEOF  = false;
        zzEOFDone = false;
        zzEndRead = zzStartRead = 0;
        zzCurrentPos = zzMarkedPos = 0;
        zzFinalHighSurrogate = 0;
        yyline = yychar = yycolumn = 0;
        zzLexicalState = YYINITIAL;
        if (zzBuffer.length > ZZ_BUFFERSIZE)
            zzBuffer = new char[ZZ_BUFFERSIZE];
    }


    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    public final String yytext() {
        return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
    }


    /**
     * Returns the character at position <tt>pos</tt> from the
     * matched text.
     *
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     *            A value from 0 to yylength()-1.
     *
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBuffer[zzStartRead+pos];
    }


    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos-zzStartRead;
    }


    /**
     * Reports an error that occured while scanning.
     *
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     *
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param   errorCode  the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        }
        catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     *
     * They will be read again by then next call of the scanning method
     *
     * @param number  the number of characters to be read again.
     *                This number must not be greater than yylength()!
     */
    public void yypushback(int number)  {
        if ( number > yylength() )
            zzScanError(ZZ_PUSHBACK_2BIG);

        zzMarkedPos -= number;
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return      the next token
     * @exception   java.io.IOException  if any I/O-Error occurs
     */
    public Token yylex() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char [] zzBufferL = zzBuffer;
        char [] zzCMapL = ZZ_CMAP;

        int [] zzTransL = ZZ_TRANS;
        int [] zzRowMapL = ZZ_ROWMAP;
        int [] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            boolean zzR = false;
            int zzCh;
            int zzCharCount;
            for (zzCurrentPosL = zzStartRead  ;
                 zzCurrentPosL < zzMarkedPosL ;
                 zzCurrentPosL += zzCharCount ) {
                zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
                zzCharCount = Character.charCount(zzCh);
                switch (zzCh) {
                    case '\u000B':
                    case '\u000C':
                    case '\u0085':
                    case '\u2028':
                    case '\u2029':
                        yyline++;
                        yycolumn = 0;
                        zzR = false;
                        break;
                    case '\r':
                        yyline++;
                        yycolumn = 0;
                        zzR = true;
                        break;
                    case '\n':
                        if (zzR)
                            zzR = false;
                        else {
                            yyline++;
                            yycolumn = 0;
                        }
                        break;
                    default:
                        zzR = false;
                        yycolumn += zzCharCount;
                }
            }

            if (zzR) {
                // peek one character ahead if it is \n (if we have counted one line too much)
                boolean zzPeek;
                if (zzMarkedPosL < zzEndReadL)
                    zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                else if (zzAtEOF)
                    zzPeek = false;
                else {
                    boolean eof = zzRefill();
                    zzEndReadL = zzEndRead;
                    zzMarkedPosL = zzMarkedPos;
                    zzBufferL = zzBuffer;
                    if (eof)
                        zzPeek = false;
                    else
                        zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                }
                if (zzPeek) yyline--;
            }
            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];

            // set up zzAction for empty match case:
            int zzAttributes = zzAttrL[zzState];
            if ( (zzAttributes & 1) == 1 ) {
                zzAction = zzState;
            }


            zzForAction: {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                        zzCurrentPosL += Character.charCount(zzInput);
                    }
                    else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    }
                    else {
                        // store back cached positions
                        zzCurrentPos  = zzCurrentPosL;
                        zzMarkedPos   = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL  = zzCurrentPos;
                        zzMarkedPosL   = zzMarkedPos;
                        zzBufferL      = zzBuffer;
                        zzEndReadL     = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        }
                        else {
                            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
                            zzCurrentPosL += Character.charCount(zzInput);
                        }
                    }
                    int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;

                    zzAttributes = zzAttrL[zzState];
                    if ( (zzAttributes & 1) == 1 ) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ( (zzAttributes & 8) == 8 ) break zzForAction;
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                zzAtEOF = true;
                return null;
            }
            else {
                switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                    case 1:
                    { Token t = new Token(yytext(),"Token not recognized",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 14: break;
                    case 2:
                    { /*Ignorar*/
                    }
                    case 15: break;
                    case 3:
                    { Token t = new Token(yytext(),"Identifier",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 16: break;
                    case 4:
                    { Token t = new Token(yytext(),"Operator",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 17: break;
                    case 5:
                    { Token t = new Token(yytext(),"ERROR, identificador no válido",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 18: break;
                    case 6:
                    { Token t = new Token(yytext(),"Separador",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 19: break;
                    case 7:
                    { Token t = new Token(yytext(),"Literal Numerico",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 20: break;
                    case 8:
                    { Token t = new Token(yytext(),"Literal String",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 21: break;
                    case 9:
                    { Token t = new Token(yytext(),"Palabra reservada",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 22: break;
                    case 10:
                    { Token t = new Token(yytext(),"ERROR, literal no válido",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 23: break;
                    case 11:
                    { Token t = new Token(yytext(),"Type",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 24: break;
                    case 12:
                    { Token t = new Token(yytext(),"Null",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 25: break;
                    case 13:
                    { Token t = new Token(yytext(),"Literal Booleano",yyline,yycolumn);tokens.add(t);return t;
                    }
                    case 26: break;
                    default:
                        zzScanError(ZZ_NO_MATCH);
                }
            }
        }
    }


}
